include: [".well-known", "birds/_/*", "birds/_small/*", "birds/_exif/*"]
exclude: [".bundle", ".sass-cache", "vendor", "helper/node_modules", "helper/.venv"]
timezone: Etc/UTC
# highlighter: none # FIXME check pre/code style rules in older posts
url: https://www.azabani.com
title: delan azabani
collections:
  talks:
  soupault_build:
    permalink: /:path
plugins:
  - jekyll-feed
feed:
  path: . # XXX hack to disable main feed
  posts_limit: 999
  tags:
    path: feed/tag/
