include: [".well-known"]
timezone: Etc/UTC
highlighter: none
url: https://www.azabani.com
title: delan azabani
plugins:
  - jekyll-feed
feed:
  path: . # XXX hack to disable main feed
  posts_limit: 999
  tags:
    path: feed/tag/
    only:
      - home
